#!/usr/bin/env bash
# Bring up the bare-metal stack (vLLM simulators + EPP + agentgateway) using
# plain `docker run` against a Docker bridge network. NO docker-compose.
#
# Layout:
#   llmd-baremetal (bridge network) ─ vllm-0   :8000
#                                   ├ vllm-1   :8000
#                                   ├ epp      :9002  (host port 9002, 9090)
#                                   └ agentgw  :8080  (host port 8080)
#
# Usage:
#   scripts/baremetal/start-stack.sh
#   curl -s -X POST http://localhost:8080/v1/chat/completions \
#     -H 'Content-Type: application/json' \
#     -d '{"model":"Qwen/Qwen3-32B","messages":[{"role":"user","content":"hi"}],"max_tokens":16}' | jq
#   scripts/baremetal/stop-stack.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

NETWORK="llmd-baremetal"
EPP_IMAGE="${EPP_IMAGE:-llm-d-epp:baremetal}"
SIM_IMAGE="${SIM_IMAGE:-ghcr.io/llm-d/llm-d-inference-sim:v0.8.2}"
# v1.2.0-alpha.2 is the first image with the inferenceRouting policy. The
# `:latest` tag still resolves to v0.12.0 (which rejects inferenceRouting).
AGW_IMAGE="${AGW_IMAGE:-ghcr.io/agentgateway/agentgateway:v1.2.0-alpha.2}"
TOKENIZER_IMAGE="${TOKENIZER_IMAGE:-ghcr.io/llm-d/llm-d-uds-tokenizer:v0.7.1}"
SIM_MODEL="${SIM_MODEL:-Qwen/Qwen3-32B}"

# TOKENIZER selects the tokenizer wiring: 'off' (default; scheduler-sim.yaml,
# no real tokenization since the simulator's prefix-cache-scorer is hash-only)
# or 'uds' (start the llm-d-uds-tokenizer container, EPP dials it for every
# request via /tmp/tokenizer/tokenizer-uds.socket).
TOKENIZER="${TOKENIZER:-off}"
TOKENIZER_VOLUME="llmd-tokenizer-uds"
TOKENIZER_HF_VOLUME="llmd-tokenizer-models"

case "$TOKENIZER" in
  off)
    SCHEDULER_CONFIG="/etc/llm-d/scheduler-sim.yaml"
    ;;
  uds)
    SCHEDULER_CONFIG="/etc/llm-d/scheduler-uds.yaml"
    ;;
  *)
    echo "TOKENIZER must be 'off' or 'uds', got: $TOKENIZER" >&2
    exit 2
    ;;
esac

say() { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
ok()  { printf '   \033[1;32m✓\033[0m %s\n' "$*"; }
die() { printf '   \033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

say "Ensuring bridge network: $NETWORK"
if ! docker network inspect "$NETWORK" >/dev/null 2>&1; then
  docker network create "$NETWORK" >/dev/null
  ok "created $NETWORK"
else
  ok "$NETWORK already exists"
fi

say "Tearing down any leftover stack containers"
for name in agentgw epp tokenizer-uds vllm-0 vllm-1; do
  docker rm -f "$name" >/dev/null 2>&1 || true
done
ok "cleaned"

if [[ "$TOKENIZER" == "uds" ]]; then
  say "Ensuring shared docker volumes for the UDS tokenizer"
  for vol in "$TOKENIZER_VOLUME" "$TOKENIZER_HF_VOLUME"; do
    if ! docker volume inspect "$vol" >/dev/null 2>&1; then
      docker volume create "$vol" >/dev/null
      ok "created $vol"
    else
      ok "$vol already exists"
    fi
  done
fi

say "Starting vLLM simulators (vllm-0, vllm-1)"
for i in 0 1; do
  docker run -d \
    --name "vllm-$i" \
    --network "$NETWORK" \
    "$SIM_IMAGE" \
    --model "$SIM_MODEL" \
    --port 8000 >/dev/null
  ok "vllm-$i started"
done

say "Waiting for simulators to become healthy"
for name in vllm-0 vllm-1; do
  for _ in $(seq 1 30); do
    if docker exec "$name" wget -qO- http://localhost:8000/health >/dev/null 2>&1; then
      ok "$name healthy"
      break
    fi
    # Some sim image variants lack wget; fall back to a curl from a transient
    # busybox container on the same network.
    if docker run --rm --network "$NETWORK" busybox:stable \
         wget -qO- "http://${name}:8000/health" >/dev/null 2>&1; then
      ok "$name healthy (via busybox)"
      break
    fi
    sleep 1
  done
done

say "Resolving simulator container IPs"
# agentgateway's inferenceRouting policy parses the EPP-returned destination
# as a Rust SocketAddr — it only accepts IP:port (not hostname:port). We
# pre-resolve the docker container IPs and write a fresh backends-docker.yaml
# that the EPP will then advertise to agentgateway.
SIM0_IP="$(docker inspect -f "{{(index .NetworkSettings.Networks \"${NETWORK}\").IPAddress}}" vllm-0)"
SIM1_IP="$(docker inspect -f "{{(index .NetworkSettings.Networks \"${NETWORK}\").IPAddress}}" vllm-1)"
[[ -n "$SIM0_IP" && -n "$SIM1_IP" ]] || die "could not resolve simulator IPs on $NETWORK"
ok "vllm-0=$SIM0_IP  vllm-1=$SIM1_IP"

GEN_BACKENDS="$ROOT/config/baremetal/backends-docker.generated.yaml"
cat > "$GEN_BACKENDS" <<EOF
# AUTO-GENERATED by start-stack.sh. Do not edit by hand. The container IPs
# are queried from docker inspect after the simulators start. Plain
# host:port (vllm-0:8000) does not work here because agentgateway parses the
# destination as a SocketAddr.
poolName: sim-pool
poolNamespace: default
targetPort: 8000
backends:
  - address: "${SIM0_IP}:8000"
    labels:
      llm-d.ai/role: decode
      app: vllm-qwen3-32b
  - address: "${SIM1_IP}:8000"
    labels:
      llm-d.ai/role: decode
      app: vllm-qwen3-32b
EOF
ok "wrote $GEN_BACKENDS"

if [[ "$TOKENIZER" == "uds" ]]; then
  say "Starting UDS tokenizer (image: $TOKENIZER_IMAGE)"
  TOK_RUN_ARGS=(
    -d
    --name tokenizer-uds
    --network "$NETWORK"
    -v "${TOKENIZER_VOLUME}:/tmp/tokenizer"
    -v "${TOKENIZER_HF_VOLUME}:/app/tokenizers"
  )
  # If HF_TOKEN is set in the environment, pass it through. Optional for
  # public models like Qwen/Qwen3-32B, required for gated ones.
  if [[ -n "${HF_TOKEN:-}" ]]; then
    TOK_RUN_ARGS+=(-e "HF_TOKEN=$HF_TOKEN")
  fi
  docker run "${TOK_RUN_ARGS[@]}" "$TOKENIZER_IMAGE" >/dev/null
  ok "tokenizer-uds started"

  say "Waiting for UDS socket to appear inside the volume"
  for _ in $(seq 1 30); do
    if docker exec tokenizer-uds test -S /tmp/tokenizer/tokenizer-uds.socket 2>/dev/null; then
      ok "UDS socket present at /tmp/tokenizer/tokenizer-uds.socket"
      break
    fi
    if [[ "$(docker inspect -f '{{.State.Running}}' tokenizer-uds 2>/dev/null)" != "true" ]]; then
      docker logs tokenizer-uds 2>&1 | tail -30
      die "tokenizer-uds exited before creating the socket"
    fi
    sleep 1
  done
fi

EPP_RUN_ARGS=(
  -d
  --name epp
  --network "$NETWORK"
  -p "127.0.0.1:9002:9002"
  -p "127.0.0.1:9003:9003"
  -p "127.0.0.1:9090:9090"
  -v "$ROOT/config/baremetal:/etc/llm-d:ro"
)
if [[ "$TOKENIZER" == "uds" ]]; then
  EPP_RUN_ARGS+=(-v "${TOKENIZER_VOLUME}:/tmp/tokenizer")
fi

say "Starting EPP (image: $EPP_IMAGE, scheduler-config: $SCHEDULER_CONFIG)"
docker run "${EPP_RUN_ARGS[@]}" "$EPP_IMAGE" \
  --baremetal \
  --backends-file=/etc/llm-d/backends-docker.generated.yaml \
  --config-file="$SCHEDULER_CONFIG" \
  --grpc-port=9002 \
  --metrics-port=9090 \
  --grpc-health-port=9003 \
  --secure-serving=false \
  --metrics-endpoint-auth=false \
  --backends-poll-interval=5s \
  >/dev/null
ok "epp started"

say "Waiting for EPP /metrics"
for _ in $(seq 1 30); do
  if curl -fsS http://127.0.0.1:9090/metrics >/dev/null 2>&1; then
    ok "/metrics is up"
    break
  fi
  if [[ "$(docker inspect -f '{{.State.Running}}' epp 2>/dev/null)" != "true" ]]; then
    docker logs epp 2>&1 | tail -30
    die "epp exited before /metrics came up"
  fi
  sleep 1
done

say "Starting agentgateway (image: $AGW_IMAGE)"
docker run -d \
  --name agentgw \
  --network "$NETWORK" \
  -p 127.0.0.1:8080:8080 \
  -v "$ROOT/config/baremetal/agentgateway.yaml:/etc/agentgateway/config.yaml:ro" \
  "$AGW_IMAGE" \
  --file /etc/agentgateway/config.yaml \
  >/dev/null
ok "agentgw started"

say "Waiting for agentgateway to listen on :8080"
for _ in $(seq 1 30); do
  if curl -fsS -o /dev/null -w '%{http_code}' http://127.0.0.1:8080/ >/dev/null 2>&1; then
    ok "agentgateway listening"
    break
  fi
  if [[ "$(docker inspect -f '{{.State.Running}}' agentgw 2>/dev/null)" != "true" ]]; then
    docker logs agentgw 2>&1 | tail -30
    die "agentgw exited before :8080 came up"
  fi
  sleep 1
done

cat <<'EOF'

  ╭───────────────────────────────────────────────────────────╮
  │  Bare-metal stack ready.                                   │
  │                                                            │
  │    agentgateway   http://127.0.0.1:8080                    │
  │    EPP ext-proc   127.0.0.1:9002 (gRPC)                   │
  │    EPP metrics    http://127.0.0.1:9090/metrics            │
  │    EPP health     127.0.0.1:9003 (gRPC)                    │
  │    vllm-0         (docker network) vllm-0:8000             │
  │    vllm-1         (docker network) vllm-1:8000             │
  │                                                            │
  │  Try:                                                      │
  │    curl -s -X POST http://127.0.0.1:8080/v1/chat/completions \
  │      -H 'Content-Type: application/json' \                 │
  │      -d '{"model":"Qwen/Qwen3-32B",                        │
  │           "messages":[{"role":"user","content":"hi"}],     │
  │           "max_tokens":16}' | jq                           │
  │                                                            │
  │  Tear down with:  scripts/baremetal/stop-stack.sh          │
  ╰───────────────────────────────────────────────────────────╯
EOF
